theme: jekyll-theme-minimal
title: TSN CBS Switch Research
description: Implementation and Performance Evaluation of a 4-Port Credit-Based Shaper TSN Switch for QoS Provisioning in Automotive Ethernet
show_downloads: true
google_analytics: 
encoding: UTF-8

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/hwkim3330/0905
  repository_name: 0905
  owner_url: https://github.com/hwkim3330
  owner_name: hwkim3330

# Navigation
navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Research Paper
    url: /paper/
  - title: GitHub
    url: https://github.com/hwkim3330/0905