# QoS Initialization Configuration
# This file initializes the QoS structure for CBS on LAN9692/9662

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/gate-enabled"
  : true

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/queue-max-sdu-table[traffic-class='0']/queue-max-sdu"
  : 1518

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/queue-max-sdu-table[traffic-class='1']/queue-max-sdu"
  : 1518

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/queue-max-sdu-table[traffic-class='2']/queue-max-sdu"
  : 1518

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/queue-max-sdu-table[traffic-class='3']/queue-max-sdu"
  : 1518

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/queue-max-sdu-table[traffic-class='4']/queue-max-sdu"
  : 1518

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/queue-max-sdu-table[traffic-class='5']/queue-max-sdu"
  : 1518

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/queue-max-sdu-table[traffic-class='6']/queue-max-sdu"
  : 1518

- ? "/ietf-interfaces:interfaces/interface[name='swp8']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/queue-max-sdu-table[traffic-class='7']/queue-max-sdu"
  : 1518

# Repeat for other ports (swp9, swp10, swp11)
- ? "/ietf-interfaces:interfaces/interface[name='swp9']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/gate-enabled"
  : true

- ? "/ietf-interfaces:interfaces/interface[name='swp10']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/gate-enabled"
  : true

- ? "/ietf-interfaces:interfaces/interface[name='swp11']/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/gate-enabled"
  : true